USE WAREHOUSE PC_STREAMSETS_WH;
USE ROLE PC_STREAMSETS_ROLE;

USE DATABASE SNOWFLAKE_SAMPLE_DATA;
USE SCHEMA TPCH_SF1;

//
// take a look at the ORDERS and LINEITEM tables
//

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS LIMIT 10;

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM LIMIT 10;


//
// view new ORDERLINEITEMS table;
// Must run pipeline as job first!!
//

USE DATABASE PC_STREAMSETS_DB;
USE SCHEMA PUBLIC;

SELECT COUNT(*) FROM  PC_STREAMSETS_DB.PUBLIC.ORDERLINEITEMS;
SELECT * FROM PC_STREAMSETS_DB.PUBLIC.ORDERLINEITEMS LIMIT 10;


//
// view data that is the basis for the Slowly Changing Dimension pipeline
//
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION LIMIT 10;
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;




USE DATABASE PC_STREAMSETS_DB;
USE SCHEMA PUBLIC;

//
// CREATE NATION DIMENSION FOR SCD PIPELINE
//

CREATE
    OR REPLACE TABLE PC_STREAMSETS_DB.PUBLIC.NATION_DIMENSION AS
SELECT
    N.N_NATIONKEY           AS NATION_KEY,
    N_NAME                  AS NATION_NAME,
    R.R_NAME                AS REGION_NAME,
    '2022-01-01T00:00:00Z'::TIMESTAMP_NTZ(0) AS START_TIMESTAMP,
    NULL::TIMESTAMP_NTZ(0)  AS END_TIMESTAMP,
    1::INTEGER              AS VERSION,
    TRUE                    AS ACTIVE_FLAG
FROM
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION N
    JOIN 
      SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION R 
    ON N_REGIONKEY = R.R_REGIONKEY;

//
// verify results
//
SELECT * FROM PC_STREAMSETS_DB.PUBLIC.NATION_DIMENSION ORDER BY NATION_KEY DESC;

//
// create nation_updates table with change data
//
CREATE OR REPLACE TABLE  PC_STREAMSETS_DB.PUBLIC.NATION_UPDATES
(
  NATION_KEY INTEGER,
  NATION_NAME VARCHAR,
  REGION_NAME VARCHAR,
  EFFECTIVE_DATE TIMESTAMP_NTZ(0) );

//
// INSERT UPDATE RECORDS
//
INSERT INTO PC_STREAMSETS_DB.PUBLIC.NATION_UPDATES
  VALUES 
    (2,'BRAZIL','AMERICA','2022-10-01T00:00:00Z')
    ,(24, 'UNITED STATES','NORTH AMERICA','2022-09-01T00:00:00Z')
    ,(25, 'AUSTRALIA','ANZ','2022-08-01T00:00:00Z') ;
 
 //
 // verify table creation
 //
 SELECT * FROM PC_STREAMSETS_DB.PUBLIC.NATION_UPDATES;